master_process off;
daemon off;



error_log  /dev/stderr  debug;

events {
    worker_connections  1024;
}

http {

    access_log /dev/stdout;

    server {
        listen       1086;
        server_name  localhost;
        location /test {
            jwt_validator;
            jwt_token_param "$arg_foo";
            jwt_token_secret_text 'JWT SECRET 123';
            proxy_pass http://google.com;
        }
    }
}
